// <auto-generated />
using System;
using ExerciseTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExerciseTracker.Migrations
{
    [DbContext(typeof(ExerciseContext))]
    [Migration("20240307132613_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0-preview.1.24081.2");

            modelBuilder.Entity("ExerciseTracker.Models.Squat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<float>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Squats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            Weight = 10f
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2024, 3, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            Weight = 12.5f
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2024, 3, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            Weight = 15f
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
