// <auto-generated />
using System;
using ExerciseTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExerciseTracker.Migrations
{
    [DbContext(typeof(ExerciseContext))]
    [Migration("20240307161419_Change Model")]
    partial class ChangeModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0-preview.1.24081.2");

            modelBuilder.Entity("ExerciseTracker.Models.Squat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Squats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comments = "Set PR at 50kg",
                            DateEnd = new DateTime(2024, 3, 5, 20, 14, 19, 373, DateTimeKind.Local).AddTicks(458),
                            DateStart = new DateTime(2024, 3, 5, 17, 14, 19, 373, DateTimeKind.Local).AddTicks(417),
                            Duration = new TimeSpan(0, 3, 0, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            Comments = "Quit after 3 reps",
                            DateEnd = new DateTime(2024, 3, 6, 17, 29, 19, 373, DateTimeKind.Local).AddTicks(468),
                            DateStart = new DateTime(2024, 3, 6, 17, 14, 19, 373, DateTimeKind.Local).AddTicks(467),
                            Duration = new TimeSpan(0, 0, 15, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            Comments = "",
                            DateEnd = new DateTime(2024, 3, 7, 19, 14, 19, 373, DateTimeKind.Local).AddTicks(472),
                            DateStart = new DateTime(2024, 3, 7, 17, 14, 19, 373, DateTimeKind.Local).AddTicks(471),
                            Duration = new TimeSpan(0, 2, 0, 0, 0)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
