// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShiftsLogger.Api.Data;

#nullable disable

namespace ShiftsLogger.Api.Migrations
{
    [DbContext(typeof(ShiftsLoggerContext))]
    [Migration("20240320103655_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.1.24081.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShiftsLogger.Shared.Models.Shift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<DateTime>("EndShift")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartShift")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkerId");

                    b.ToTable("Shifts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Duration = new TimeSpan(0, 2, 0, 0, 0),
                            EndShift = new DateTime(2024, 3, 15, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StartShift = new DateTime(2024, 3, 15, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 1
                        },
                        new
                        {
                            Id = 2,
                            Duration = new TimeSpan(0, 2, 0, 0, 0),
                            EndShift = new DateTime(2024, 3, 15, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartShift = new DateTime(2024, 3, 15, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 1
                        },
                        new
                        {
                            Id = 3,
                            Duration = new TimeSpan(0, 3, 0, 0, 0),
                            EndShift = new DateTime(2024, 3, 15, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartShift = new DateTime(2024, 3, 15, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 1
                        },
                        new
                        {
                            Id = 4,
                            Duration = new TimeSpan(0, 2, 0, 0, 0),
                            EndShift = new DateTime(2024, 3, 16, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StartShift = new DateTime(2024, 3, 16, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 1
                        },
                        new
                        {
                            Id = 5,
                            Duration = new TimeSpan(0, 2, 0, 0, 0),
                            EndShift = new DateTime(2024, 3, 16, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartShift = new DateTime(2024, 3, 16, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 1
                        },
                        new
                        {
                            Id = 6,
                            Duration = new TimeSpan(0, 3, 0, 0, 0),
                            EndShift = new DateTime(2024, 3, 16, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartShift = new DateTime(2024, 3, 16, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 1
                        },
                        new
                        {
                            Id = 7,
                            Duration = new TimeSpan(0, 2, 0, 0, 0),
                            EndShift = new DateTime(2024, 3, 17, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StartShift = new DateTime(2024, 3, 17, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 1
                        },
                        new
                        {
                            Id = 8,
                            Duration = new TimeSpan(0, 2, 0, 0, 0),
                            EndShift = new DateTime(2024, 3, 17, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartShift = new DateTime(2024, 3, 17, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 1
                        },
                        new
                        {
                            Id = 9,
                            Duration = new TimeSpan(0, 3, 0, 0, 0),
                            EndShift = new DateTime(2024, 3, 17, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartShift = new DateTime(2024, 3, 17, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 1
                        },
                        new
                        {
                            Id = 10,
                            Duration = new TimeSpan(0, 2, 0, 0, 0),
                            EndShift = new DateTime(2024, 3, 15, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StartShift = new DateTime(2024, 3, 15, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 2
                        },
                        new
                        {
                            Id = 11,
                            Duration = new TimeSpan(0, 2, 0, 0, 0),
                            EndShift = new DateTime(2024, 3, 15, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartShift = new DateTime(2024, 3, 15, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 2
                        },
                        new
                        {
                            Id = 12,
                            Duration = new TimeSpan(0, 3, 0, 0, 0),
                            EndShift = new DateTime(2024, 3, 15, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartShift = new DateTime(2024, 3, 15, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 2
                        },
                        new
                        {
                            Id = 13,
                            Duration = new TimeSpan(0, 2, 0, 0, 0),
                            EndShift = new DateTime(2024, 3, 16, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StartShift = new DateTime(2024, 3, 16, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 2
                        },
                        new
                        {
                            Id = 14,
                            Duration = new TimeSpan(0, 2, 0, 0, 0),
                            EndShift = new DateTime(2024, 3, 16, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartShift = new DateTime(2024, 3, 16, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 2
                        },
                        new
                        {
                            Id = 15,
                            Duration = new TimeSpan(0, 3, 0, 0, 0),
                            EndShift = new DateTime(2024, 3, 16, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartShift = new DateTime(2024, 3, 16, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 2
                        },
                        new
                        {
                            Id = 16,
                            Duration = new TimeSpan(0, 2, 0, 0, 0),
                            EndShift = new DateTime(2024, 3, 17, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StartShift = new DateTime(2024, 3, 17, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 2
                        },
                        new
                        {
                            Id = 17,
                            Duration = new TimeSpan(0, 2, 0, 0, 0),
                            EndShift = new DateTime(2024, 3, 17, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartShift = new DateTime(2024, 3, 17, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 2
                        },
                        new
                        {
                            Id = 18,
                            Duration = new TimeSpan(0, 3, 0, 0, 0),
                            EndShift = new DateTime(2024, 3, 17, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartShift = new DateTime(2024, 3, 17, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 2
                        },
                        new
                        {
                            Id = 19,
                            Duration = new TimeSpan(0, 2, 0, 0, 0),
                            EndShift = new DateTime(2024, 3, 15, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StartShift = new DateTime(2024, 3, 15, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 3
                        },
                        new
                        {
                            Id = 20,
                            Duration = new TimeSpan(0, 2, 0, 0, 0),
                            EndShift = new DateTime(2024, 3, 15, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartShift = new DateTime(2024, 3, 15, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 3
                        },
                        new
                        {
                            Id = 21,
                            Duration = new TimeSpan(0, 3, 0, 0, 0),
                            EndShift = new DateTime(2024, 3, 15, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartShift = new DateTime(2024, 3, 15, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 3
                        },
                        new
                        {
                            Id = 22,
                            Duration = new TimeSpan(0, 2, 0, 0, 0),
                            EndShift = new DateTime(2024, 3, 16, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StartShift = new DateTime(2024, 3, 16, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 3
                        },
                        new
                        {
                            Id = 23,
                            Duration = new TimeSpan(0, 2, 0, 0, 0),
                            EndShift = new DateTime(2024, 3, 16, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartShift = new DateTime(2024, 3, 16, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 3
                        },
                        new
                        {
                            Id = 24,
                            Duration = new TimeSpan(0, 3, 0, 0, 0),
                            EndShift = new DateTime(2024, 3, 16, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartShift = new DateTime(2024, 3, 16, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 3
                        },
                        new
                        {
                            Id = 25,
                            Duration = new TimeSpan(0, 2, 0, 0, 0),
                            EndShift = new DateTime(2024, 3, 17, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StartShift = new DateTime(2024, 3, 17, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 3
                        },
                        new
                        {
                            Id = 26,
                            Duration = new TimeSpan(0, 2, 0, 0, 0),
                            EndShift = new DateTime(2024, 3, 17, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartShift = new DateTime(2024, 3, 17, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 3
                        },
                        new
                        {
                            Id = 27,
                            Duration = new TimeSpan(0, 3, 0, 0, 0),
                            EndShift = new DateTime(2024, 3, 17, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartShift = new DateTime(2024, 3, 17, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 3
                        },
                        new
                        {
                            Id = 28,
                            Duration = new TimeSpan(0, 2, 0, 0, 0),
                            EndShift = new DateTime(2024, 3, 15, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StartShift = new DateTime(2024, 3, 15, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 4
                        },
                        new
                        {
                            Id = 29,
                            Duration = new TimeSpan(0, 2, 0, 0, 0),
                            EndShift = new DateTime(2024, 3, 15, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartShift = new DateTime(2024, 3, 15, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 4
                        },
                        new
                        {
                            Id = 30,
                            Duration = new TimeSpan(0, 3, 0, 0, 0),
                            EndShift = new DateTime(2024, 3, 15, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartShift = new DateTime(2024, 3, 15, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 4
                        },
                        new
                        {
                            Id = 31,
                            Duration = new TimeSpan(0, 2, 0, 0, 0),
                            EndShift = new DateTime(2024, 3, 16, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StartShift = new DateTime(2024, 3, 16, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 4
                        },
                        new
                        {
                            Id = 32,
                            Duration = new TimeSpan(0, 2, 0, 0, 0),
                            EndShift = new DateTime(2024, 3, 16, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartShift = new DateTime(2024, 3, 16, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 4
                        },
                        new
                        {
                            Id = 33,
                            Duration = new TimeSpan(0, 3, 0, 0, 0),
                            EndShift = new DateTime(2024, 3, 16, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartShift = new DateTime(2024, 3, 16, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 4
                        },
                        new
                        {
                            Id = 34,
                            Duration = new TimeSpan(0, 2, 0, 0, 0),
                            EndShift = new DateTime(2024, 3, 17, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StartShift = new DateTime(2024, 3, 17, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 4
                        },
                        new
                        {
                            Id = 35,
                            Duration = new TimeSpan(0, 2, 0, 0, 0),
                            EndShift = new DateTime(2024, 3, 17, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartShift = new DateTime(2024, 3, 17, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 4
                        },
                        new
                        {
                            Id = 36,
                            Duration = new TimeSpan(0, 3, 0, 0, 0),
                            EndShift = new DateTime(2024, 3, 17, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartShift = new DateTime(2024, 3, 17, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 4
                        });
                });

            modelBuilder.Entity("ShiftsLogger.Shared.Models.Worker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Workers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Henk"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Ingrid"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Jan"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Helena"
                        });
                });

            modelBuilder.Entity("ShiftsLogger.Shared.Models.Shift", b =>
                {
                    b.HasOne("ShiftsLogger.Shared.Models.Worker", "Worker")
                        .WithMany("Shifts")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("ShiftsLogger.Shared.Models.Worker", b =>
                {
                    b.Navigation("Shifts");
                });
#pragma warning restore 612, 618
        }
    }
}
