// <auto-generated />
using System;
using HabitLoggerMvc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HabitLoggerMvc.Migrations
{
    [DbContext(typeof(HabitLoggerContext))]
    [Migration("20240309195209_add-seed-data")]
    partial class addseeddata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.1.24081.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HabitLoggerMvc.Models.Habit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HabitUnitId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HabitUnitId");

                    b.ToTable("Habits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HabitUnitId = 1,
                            Name = "Drinking water"
                        },
                        new
                        {
                            Id = 2,
                            HabitUnitId = 2,
                            Name = "Drinking fruit sap"
                        },
                        new
                        {
                            Id = 3,
                            HabitUnitId = 3,
                            Name = "Walking"
                        },
                        new
                        {
                            Id = 4,
                            HabitUnitId = 4,
                            Name = "Meditation"
                        },
                        new
                        {
                            Id = 5,
                            HabitUnitId = 5,
                            Name = "Reading"
                        });
                });

            modelBuilder.Entity("HabitLoggerMvc.Models.HabitLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("HabitId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HabitId");

                    b.ToTable("HabitLogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateOnly(2023, 1, 1),
                            HabitId = 1,
                            Quantity = 8
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateOnly(2023, 1, 2),
                            HabitId = 2,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateOnly(2023, 1, 3),
                            HabitId = 3,
                            Quantity = 3
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateOnly(2023, 1, 4),
                            HabitId = 1,
                            Quantity = 7
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateOnly(2023, 1, 5),
                            HabitId = 2,
                            Quantity = 4
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateOnly(2023, 1, 6),
                            HabitId = 4,
                            Quantity = 30
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateOnly(2023, 1, 7),
                            HabitId = 5,
                            Quantity = 150
                        });
                });

            modelBuilder.Entity("HabitLoggerMvc.Models.HabitUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HabitUnits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Medium glass"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Small glass"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Meters"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Minutes"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Pages"
                        });
                });

            modelBuilder.Entity("HabitLoggerMvc.Models.Habit", b =>
                {
                    b.HasOne("HabitLoggerMvc.Models.HabitUnit", null)
                        .WithMany()
                        .HasForeignKey("HabitUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HabitLoggerMvc.Models.HabitLog", b =>
                {
                    b.HasOne("HabitLoggerMvc.Models.Habit", null)
                        .WithMany()
                        .HasForeignKey("HabitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
